### ISSUE TITLE
Why does the Processor icon become particularly large after moving it?

### ISSUE THREAD

**Issue by pelva** [ObeoNetwork/Flow-Designer#33]
https://github.com/ObeoNetwork/Flow-Designer/assets/135562884/0e30131f-3e88-4678-bb8c-2648a530eec4

The operation is as shown in the video,Is this normal or is it a bug?

**Comment by pcdavid** [comment]
Hi. This looks similar to https://bugs.eclipse.org/bugs/show_bug.cgi?id=576423 which has normally been fixed in Sirius 7.0.0. Can you indicate the version of Sirius you are using?

**Comment by lredor** [comment]
HI,
You're right @pcdavid, the problem is linked. But it seems that it does not cover all cases. I will create an issue on Sirius side to fix this problem.
However, it would be preferable if @pelva confirms the version used.

**Comment by lredor** [comment]
The corresponding Sirius issue is https://github.com/eclipse-sirius/sirius-desktop/issues/331.

**Comment by pelva** [comment]
I followed the instructions in the Readme and installed ObeoDesigner-Community-11.5-win32.win32.x86_64. I found that the Sirius version used was 6.5.1 .
If it's been fixed, that's no problem.
![image](https://github.com/ObeoNetwork/Flow-Designer/assets/135562884/d7d62d18-1f33-464a-896b-382066d8f91a)

**Comment by lredor** [comment]
@pelva Two information:
* Thanks for your feedback. The problem is partially fixed since the version you used, but not fully. I will update the README because a newer version of OD is available (with at least the fix mentioned by Pierre-Charles).
* I've just pushed a new fix on Sirius side ([PR #332](https://github.com/eclipse-sirius/sirius-desktop/pull/332)). A release of Sirius is in progress (7.4.1), but the code is currently freezed so I think that I need to wait next version to merged by PR.

**Comment by lredor** [comment]
The fix has been merged in Sirius, for the next release (7.4.1). A corresponding Obeo Designer version, 11.9.0, will be release soon (in few weeks/months?). So the current problem will be fixed without any change in Flow Designer.

**Comment by pelva** [comment]
Thanks for the reply, you guys are doing a great job!
